---
title: "Base de datos"
author: "Osmar Dominique"
date: "2025-08-20"
output: html_document
---

Se considerará una base de datos sobre distintas familias en cierto municipio que quieren comprar o alquilar casas y en base a ciertas variables se decidirá a quién se le venderá o alquilará la vivienda que solicitan.

```{r}
library(dplyr)
datos <- read.csv("C:/Users/Alumno 25-B/Documents/Osmar/Analítica/Trabajo 3/comprar_alquilar.csv", header = TRUE, sep = ",")
```

Las variables consideradas son:

## Datos cualitativos

* Estado civil

```{r}
estado <- recode(datos$estado_civil,
                             "0" = "Soltero",
                             "1" = "Casado",
                             "2" = "Divorciado")

barplot(table(estado), main = "Familias por el estado civil del comprador(es)", col = c("gray", "yellow", "black"), xlab = "Estado civil", ylab = "Número de familias")
```

```{r}
job <- recode(datos$trabajo,
                             "0" = "Sin empleo",
                             "1" = "Autónomo",
                             "2" = "Empleado",
                             "3" = "Empresario",
                             "4" = "Pareja: autónomos",
                             "5" = "Pareja: empleados",
                             "6" = "Pareja: autónomo y asalariado",
                             "7" = "Pareja: empresario y autónomo",
                             "8" = "Pareja: empresarios los dos, o empresario y empleado")

barplot(table(job), main = "Familias por trabajo", col = c("black", "blue", "blue", "blue", "red", "red", "red", "red", "red"), xlab = "Trabajo", ylab = "Número de familias")
```

```{r}
compra <- recode(datos$comprar,
                             "0" = "Soltero",
                             "1" = "Casado",
                             "2" = "Divorciado")

barplot(table(compra), main = "Familias por el estado civil del comprador(es)", col = c("gray", "yellow", "black"), xlab = "Estado civil", ylab = "Número de familias")
```
















