library(readxl)
REMEDOMEX <- read_excel("REMEDOMEX.xlsx")
View(REMEDOMEX)
data <- data.frame(REMEDOMEX)
library(readxl)
REMEDOMEX <- read_excel("REMEDOMEX.xlsx")
View(REMEDOMEX)
data <- data.frame(REMEDOMEX)
info <- data.frame(REMEDOMEX)